name: ci-helm

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull_request
        run: |
          changed=$(ct list-changed --config=.ct.yml --target-branch ${{ github.event.repository.default_branch }})
